# Generated by Django 2.2.14 on 2025-02-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wallet',
            name='bonus',
            field=models.CharField(default='0.00', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_wallet',
            name='loans',
            field=models.CharField(default='0.00', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_wallet',
            name='total_balance',
            field=models.CharField(default='0.00', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_wallet',
            name='unverified',
            field=models.CharField(default='0.00', max_length=200),
        ),
    ]
