# Generated by Django 5.2 on 2026-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='account_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='cot_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tax_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
