# Generated by Django 5.2 on 2026-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customerprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
