# Generated by Django 5.1.6 on 2025-09-03 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_wallet_id_transaction_transactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
