# Generated by Django 5.1.6 on 2025-09-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_transaction_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('NIN', 'National ID (NIN)'), ('PASSPORT', 'International Passport'), ('DL', 'Driver’s License'), ('PVC', 'Voter’s Card')], max_length=50, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='kyc_docs/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='kyc_docs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
