# Generated by Django 5.1.6 on 2025-09-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('NIN', 'National Identity Number'), ('PASSPORT', 'International Passport'), ('DL', 'Driver’s License'), ('PVC', 'Voter’s Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/back/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/front/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
